version: '3.8'
services: 
  task:
    image: node:latest
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host --port 5001"
    volumes:
      - .:/app
    ports:
      - "5001:5001"